import {Marcellus, Montserrat} from "next/font/google";
import "./globals.css";

import Header from "@/components/ui/Header";
import CursorProvider from "@/components/ui/CursorContext";
import Transition from "@/components/ui/Transition";
import PageTransition from "@/components/ui/PageTransition";

/*const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});*/

const marcellus = Marcellus({
  subsets: ["latin"], 
  weight: ["400"], 
  variable: "--font-marcellus",
});

const montserrat = Montserrat({
  subsets: ["latin"], 
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], 
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-screen">
      <body className={`${marcellus.variable} ${montserrat.variable} overflow-x-hidden`}>
        <CursorProvider>
          <Transition />
          <Header/>
          <PageTransition>{children}</PageTransition>
        </CursorProvider>
      </body>
    </html>
  );
}
